version: '2'
services:
  gocd-server:
    image: gocd/gocd-server:v17.4.0
    container_name: gocd-server
    volumes:
      - ./gocd/plugins:/godata/plugins/external/
      - ./gocd/ssh/key:/home/go/.ssh/
      - ./gocd/ssh/config:/etc/ssh/
      - ./gocd/go-server:/godata/config/
    ports:
      - "8153:8153"
      - "8154:8154"
      
  gocd-agent:
    image: go-agent:latest
    container_name: gocd-agent
    volumes:
      - ./gocd/ssh/key:/home/go/.ssh/
      - ./gocd/ssh/config:/etc/ssh/
    build:
      context: ./gocd/go-agent

  postgres:
    image: postgres:9.6.3
    container_name: database-leave
    environment:
      - POSTGRES_USER=leave-backend
    ports:
      - "5432:5432"
