version: '2'
services:
  leave-vault:
    image: vault
    container_name: leave-vault
    ports:
      - "0.0.0.0:8200:8200"
    volumes:
      - ./vault-server/file:/vault/file:rw
      - ./vault-server/config:/vault/config:rw
      - ./vault-server/certs/:/vault/certs:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/

  gocd-server:
    image: gocd/gocd-server:v17.4.0
    container_name: gocd-server
    volumes:
      - ./gocd/plugins:/godata/plugins/external/
      - ./gocd/ssh/key:/home/go/.ssh/
      - ./gocd/ssh/config:/etc/ssh/
      - ./gocd/go-server:/godata/config/
    ports:
      - "8153:8153"
      - "8154:8154"

  gocd-agent:
    image: go-agent:latest
    container_name: gocd-agent
    build:
      context: ./gocd/go-agent
    links:
      - gocd-server
