---
- hosts: all

  tasks:

    - include_vars: "./vars/secrets.yml"

    - name: Adding docker repository key
      apt_key:
        data: "{{ lookup('file', './pubkeys/docker.repo.gpg') }}"
        state: present
      become: yes

    - name: Adding docker repository
      apt_repository:
        repo:  deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty stable
        state: present
      become: yes

    - name: Ensure packages are installed
      package:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        - git
        - docker-ce
        - python-pip

    - name: Install pip packages required for docker
      pip:
        name: "{{ item }}"
      become: yes
      with_items:
        - docker-compose

    - name: Accept gitlab ssh host key
      known_hosts:
        name: git.thoughtworks.net
        key: "{{ lookup('file', 'pubkeys/git.thoughtworks.net') }}"

    - name: Add ssh pub keys for gitlab
      copy:
        src: ./pubkeys/gitlab_rsa.pub
        dest: ~/.ssh/

    - name: Add ssh priv keys for gitlab
      copy:
        content: "{{ private_gitlab_ssh_key }}"
        dest: ~/.ssh/gitlab_rsa
        mode: 0400

    - name: Clone infraestructure git repo
      git:
        repo: git@git.thoughtworks.net:leave/infraestructura.git
        dest: ~/infraestructura/
        clone: yes
        key_file: ~/.ssh/gitlab_rsa

    - name: Copy docker-compose.yml to home folder
      copy:
        src: ~/infraestructura/docker-compose.yml
        dest: ~/docker-compose.yml
        remote_src: True

    - docker_service:
        project_src: gocd-server
        state: absent
      connection: local
